version: '2'
services:
    avalia10-app:
        image: avalia10
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://avalia10-mysql:3306/avalia10?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    avalia10-mysql:
        extends:
            file: mysql.yml
            service: avalia10-mysql
